name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
          - mipsel-unknown-linux-musl

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust Nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          # We do NOT need to install the 'targets' here because:
          # 1. We use 'cross' (which provides the linker/sysroot).
          # 2. We use '-Z build-std' (which compiles std from source).
          #targets: ${{ matrix.target }}
          components: rust-src

      - name: Install cross (via binstall)
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall cross -y

      - name: Build using Cross
        run: |
          cross +nightly build --target ${{ matrix.target }} \
            -Z build-std=std,core,alloc,panic_unwind \
            --release

      - name: Prepare Asset
        shell: bash
        run: |
          PROJECT_NAME="wireguard-keepalived"
          BINARY_PATH="target/${{ matrix.target }}/release/$PROJECT_NAME"
          NEW_NAME="${PROJECT_NAME}-${{ matrix.target }}"
          mv $BINARY_PATH $NEW_NAME

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: wireguard-keepalived-${{ matrix.target }}
